services:
  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jcasbin-sample
    ports:
      - 6543:5432

  casbin-run:
    image: jcasbin-sample
    build:
      context: .
    environment:
      DB_PORT: 5432
      DB_HOST: postgres-db
    command: bash -c "java -jar run.jar db-setup && java -jar run.jar benchmark && java -jar run.jar check ale domain1 course1 read && java -jar run.jar check ale domain1 data2 write"
    depends_on:
      - postgres-db